name: Build Mac DMG

on:
  push:
    tags:
      - 'v*' # 当你推送 tag，如 v1.0.1 时触发

jobs:
  build-mac:
    runs-on: macos-latest

    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 23

      - name: Install dependencies
        run: npm install

      - name: Build and publish to GitHub Releases
        run: npm run publish:mac_github
