name: Build Windows EXE

on:
  push:
    tags:
      - 'v*'

jobs:
  build-win:
    runs-on: windows-latest

    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Build electron app (generate out/main/index.js)
        run: npm run build
      - name: Check out/main exists
        run: Get-ChildItem -Path out/main/index.js -Recurse
      - name: Generate win-unpacked
        run: npx electron-builder --win --dir
      - name: Check win-unpacked contents
        run: Get-ChildItem -Path dist/win-unpacked -Recurse

      - name: Install NSIS
        run: choco install nsis -y

      - name: Build installer & publish
        run: npx electron-builder --win --publish always
