name: Build Windows EXE

on:
  push:
    tags:
      - 'v*' # 推送版本标签时触发，如 v1.0.1

jobs:
  build-win:
    runs-on: windows-latest

    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # 建议使用 LTS 版本（如 18）

      - name: Install dependencies
        run: npm install
      - name: Install NSIS
        run: choco install nsis -y
      - name: Build and publish to GitHub Releases
        run: npm run publish:win_github
