name: Build Windows EXE

on:
  push:
    tags:
      - 'v*'

jobs:
  build-win:
    runs-on: windows-latest

    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Build electron app (generate out/main/index.js)
        run: npm run build

      - name: Check out/main exists
        run: dir /s /b out\main\index.js

      - name: Install NSIS
        run: choco install nsis -y

      - name: Build installer & publish
        run: npm run publish:win_github
